version: '3.7'

services:
  app:
    container_name: app-container
    build: .
  postgres-db:
    image: postgres:latest
    container_name: pg-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banking_service
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: